### ISSUE TITLE
Allow CORS allowlist to be configured

### ISSUE THREAD

**Issue by scy** [AKVorrat/dearmep#119]
Should be configurable via the config YAML, e.g.:

```yaml
api:
  cors:
    origins:
      - https://example.org
      - https://www.example.org
```

This should be fed directly to FastAPI’s/Starlette’s `CORSMiddleware`.
