### ISSUE TITLE
Maintenance message: Inline styles are being stripped

### ISSUE THREAD

**Issue by scy** [AKVorrat/dearmep#242]
I've tried wrapping the maintenance message in `<span style="color: salmon;">…</span>`, but it's displayed as `<span>…</span>` without any attributes instead. I think it would be helpful if campaigns could provide inline styles. Is there a way to convince whatever is sanitizing this HTML to allow inline styles? Links work fine.

For the record, this is the message that's currently live:

```yaml
    # Message to display in maintenance mode. HTML allowed.
    maintenance.message:
      en: '<span style="color: salmon;">The <em>DearMEP</em> team is currently at the <a href="https://events.ccc.de/congress/2023/" target="_blank">37th Chaos Communication Congress</a> at the <a href="https://37c3.c3nav.de/l/epicenter/details/" target="_blank">epicenter.works assembly</a> and available for questions, ideas, or even demonstrations of the system. Therefore, you currently cannot call real Members of the European Parliament here. Instead, you will be connected to our demo phone, regardless of whom you select.</span>'
      de: '<span style="color: salmon;">Das <em>DearMEP</em>-Team ist aktuell auf dem <a href="https://events.ccc.de/congress/2023/" target="_blank">37. Chaos Communication Congress</a> bei der <a href="https://37c3.c3nav.de/l/epicenter/details/" target="_blank">epicenter.works-Assembly</a> und steht dort für Fragen, Ideen oder auch Demonstrationen des Systems zur Verfügung. Deshalb kannst du hier aktuell keine echten Mitglieder des Europäischen Parlamentes anrufen. Stattdessen wirst du auf unser Demo-Telefon verbunden, egal wen du auswählst.</span>'
```
